INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("2", "PRD-suivi-ast-tc", NULL, "Bréguet-Cluster B", "Obsolete");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("1", "PRD-dsdir2-export", NULL, "Bréguet-Cluster B", "Obsolete");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("3", "PRD-NEWAPPLY", NULL, "Bréguet-Cluster B", "Obsolete");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("5", "prd-accueil.centralesupelec.fr", NULL, "Bréguet-Cluster A", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("7", "PRD-Mercanet", NULL, "Bréguet-Cluster A", "Obsolete");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("8", "LSI-audit-WIN7", NULL, "Bréguet-Cluster A", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("6", "vgwin7saclay-prd", NULL, "Bréguet-Cluster A", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("9", "suptests", NULL, "Bréguet-Cluster A", "Obsolete: ancien serveur de gestion de jeux de tests applicatifs");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("10", "crig-antivir", NULL, "Bréguet-Cluster A", "Serveur antivirus");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("11", "PRD-LANDESK-BDD", NULL, "Bréguet-Cluster A", "Serveur LANDesk (gestion des postes utilisateurs)");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("12", "PRD-AGENTLANDESK", NULL, "Bréguet-Cluster A", "Serveur LANDesk (gestion des postes utilisateurs)");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("13", "PRD-LANDESK", NULL, "Bréguet-Cluster A", "Serveur LANDesk (gestion des postes utilisateurs) en cours de migration vers Ivanti");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("14", "PRD-IVANTI", NULL, "Bréguet-Cluster A", "Serveur Ivanti (nouvelle version LANDesk)");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("16", "gvdepannage", NULL, "Bréguet-Cluster A", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("17", "dhcp1.centralesupelec.fr", NULL, "Bréguet-Cluster A", "Serveur DHCP de Saclay");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("15", "crig-wsus", NULL, "Bréguet-Cluster A", "Serveur de gesiton des mises à jour Microsoft");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("18", "gw-ministudio", NULL, "Bréguet-Cluster A", "Passerelle réseau pour le VLAN mini-studio (bat. Bréguet)");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("19", "supelec", NULL, "Bréguet-Cluster A", "Serveur DNS public (zone supelec.fr)");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("20", "infogif", NULL, "Bréguet-Cluster A", "Serveur DNS public");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("22", "newns.centralesupelec.fr", NULL, "Bréguet-Cluster A", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("21", "resolv1.centralesupelec.fr", NULL, "Bréguet-Cluster A", "Resolver campus Saclay");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("23", "resolv-priv", NULL, "Bréguet-Cluster A", "Serveur de résolution DNS des clients du bâtiment Bréguet");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("24", "ns-master.centralesupelec.fr", NULL, "Bréguet-Cluster A", "Serveur maître caché DNS");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("25", "piston", NULL, "Bréguet-Cluster A", "NS ex-ECP");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("26", "PRD-NS1", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("27", "ns1-saclay.centralesupelec.fr", NULL, "Bréguet-Cluster A", "Serveur DNS public Saclay");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("28", "netdiag.centralesupelec.fr", NULL, "Bréguet-Cluster A", "Serveur de diagnostique réseau");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("29", "TST-NETMAGIS", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("30", "PRD-NETMAGIS", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("31", "vl-wizard.centralesupelec.fr", NULL, "Bréguet-Cluster A", "Nouveau serveur de gestion de microswitches (pas en production)");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("32", "coderepo-priv", NULL, "Bréguet-Cluster A", "Ancien serveur de versionning de code (vérifier les dépôts, ");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("33", "nmp.centralesupelec.fr", NULL, "Bréguet-Cluster A", "Serveur de gestion des microswitches Bouygues/Effeil");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("34", "speedtest.centralesupelec.fr", NULL, "Bréguet-Cluster A", "Serveur de tests de débits");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("35", "radius2.centralesupelec.fr", NULL, "Bréguet-Cluster A", "Serveru d'authentification Wifi Radius");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("36", "radius2", NULL, "Bréguet-Cluster A", "Serveur Radius  Bréguet (en cours de migration sur le nouveau serveur)");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("37", "radius1.centralesupelec.fr", NULL, "Bréguet-Cluster A", "Serveur d'authentification WiFi (Radius)");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("38", "PRD-RADIATOR1", NULL, "Bréguet-Cluster B", "Obsolete");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("39", "PRD-RADIATOR2", NULL, "Bréguet-Cluster B", "Obsolete");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("40", "prd-fw-concours.centralesupelec.fr", NULL, "Bréguet-Cluster A", "Pare-feu du réseau concours (N. Boullis)");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("41", "TST-CSTRANSFERT", NULL, "Bréguet-Cluster A", "Transfert de fichiers");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("43", "PRD-PHLEGYAS", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("44", "rebond-eleves", NULL, "Bréguet-Cluster A", "Serveur de rebond SSH pour les élèves dans le batiment Bréguet (programmer sa suppression)");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("42", "PRD-CHARON", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("45", "rebond", NULL, "Bréguet-Cluster A", "Passerelle SSH Bréguet, en voie de migration sur le nouveau serveur");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("46", "rebondecp", NULL, "Bréguet-Cluster A", "Obsolete: passerelle de rebond SSH pour Châtenay");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("47", "Cisco-Prime", NULL, "Bréguet-Cluster A", "Supervision coeur de réseau CISCO et WiFi");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("48", "zabbix.centralesupelec.fr", NULL, "Bréguet-Cluster A", "Serveur de métrologie du réseau");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("49", "netdisco.centralesupelec.fr", NULL, "Bréguet-Cluster A", "Serveur de supervision des infrastructures réseau");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("50", "supervise", NULL, "Bréguet-Cluster A", "Serveur d'outils de supervision réseau (Netdisco, ...)");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("51", "ntp1.centralesupelec.fr", NULL, "Bréguet-Cluster A", "Serveur de temps");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("52", "NA", NULL, "NA", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("54", "vpneleves", NULL, "Bréguet-Cluster A", "Obsolete: ancien serveur VPN des élèves. A eteindre");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("53", "netmagis.centralesupelec.fr", NULL, "Bréguet-Cluster A", "Serveur de gestion DNS/DHCP mutualisé (délégation de gestion aux laboratoires)");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("55", "vpn-clients-saclay1.centralesupelec.fr", NULL, "Bréguet-Cluster A", "Serveur VPN clients mobiles");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("56", "vpn-clients-saclay2.centralesupelec.fr", NULL, "Bréguet-Cluster A", "Serveur VPN clients mobiles");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("57", "certs-vpn.centralesupelec.fr", NULL, "Bréguet-Cluster A", "Serveur de gestion des configurations VPN client mobile");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("58", "ra-supki", NULL, "Bréguet-Cluster A", "Obsolete: ancien serveur d'émission de certificats VPN Gif");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("59", "criovpn4", NULL, "Bréguet-Cluster A", "Obsolete: Ancien serveur VPN clients mobiles de Bréguet.");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("60", "tst-new-cluster", NULL, "Bréguet-Cluster B", "Obsolete");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("61", "PRD-CLUSTIN", NULL, "Bréguet-Cluster B", "Obsolete ?");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("62", "cri-bt", NULL, "Bréguet-Cluster A", "Obsolete: ancien serveur bugzilla");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("63", "TST-RACKTABLES", NULL, "Bréguet-Cluster A", "DCIM-lite");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("64", "ansible.centralesupelec.fr", NULL, "Bréguet-Cluster A", "Serveur de gestion de déploiement et de versionning des configurations de VMs");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("65", "PRD-NETLOG", NULL, "Bréguet-Cluster A", "VM de centralisation de logs réseau");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("66", "syslog-saclay.centralesupelec.fr", NULL, "Bréguet-Cluster A", "Serveur de logs serveur");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("67", "PRD-RSYSLOG", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("68", "PRD-EM2C-S06", NULL, "Bréguet-Cluster A", "Serveur CrashPlan EM2C");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("69", "PRD-SAVE_LGI", NULL, "Bréguet-Cluster A", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("70", "PRD-VEEAM-PROXY-RENNES", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("71", "PRD-VEEAM-ECP", NULL, "Bréguet-Cluster B", "Obsolete");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("72", "veeamproxy-gif1", NULL, "Bréguet-Cluster A", "Proxy Veeam pour les backups de VMs");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("73", "veeambr", NULL, "Bréguet-Cluster A", "Serveur de gestion des sauvegardes VMs");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("74", "crig-veeam1", NULL, "Bréguet-Cluster A", "OBSOLETE: ancien serveur Veeam1 et ancienne base de données VeeamBR");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("75", "jessie-8", NULL, "Bréguet-Cluster A", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("76", "TP-OpenNebula-Template-Debian8-20170515", NULL, "Bréguet-Cluster A", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("77", "wordpress-modele", NULL, "Bréguet-Cluster A", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("78", "centos6", NULL, "Bréguet-Cluster A", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("79", "Ansible-Debian9", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("80", "centos7", NULL, "Bréguet-Cluster A", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("81", "Ansible-Ubuntu1604", NULL, "Bréguet-Cluster A", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("82", "Ansible-Debian8", NULL, "Bréguet-Cluster A", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("83", "tpl-windows 2016 srv", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("84", "squeeze-6", NULL, "Bréguet-Cluster A", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("85", "centos6-template-rennes", NULL, "Bréguet-Cluster A", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("86", "tpl-centos7-vmtools", NULL, "Bréguet-Cluster A", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("87", "tpl-srv 2012 R2 (64 Bits)", NULL, "Bréguet-Cluster A", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("88", "TP-OpenNebula-Template-Debian8-20180606", NULL, "Bréguet-Cluster A", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("89", "rhel-58", NULL, "Bréguet-Cluster A", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("90", "ubuntu_16-04-01_LTS", NULL, "Bréguet-Cluster A", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("91", "tpl-centos7", NULL, "Bréguet-Cluster A", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("92", "tpl-srv 2016", NULL, "Bréguet-Cluster A", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("93", "vgwin7saclay", NULL, "Bréguet-Cluster A", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("94", "TST-WIN7_3", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("95", "tpl-srv 2008r2 - without ipv6", NULL, "Bréguet-Cluster A", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("96", "wheezy-7", NULL, "Bréguet-Cluster A", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("97", "vcenter5", NULL, "Bréguet-Cluster A", "Serveur vmWare de gestion des Clusters CS-Saclay");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("98", "teaming- production", NULL, "Bréguet-Cluster A", "Ancien Intranet conservé pour archives");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("99", "PRD-NUXEO-LDAP", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("100", "open-project.centralesupelec.fr", NULL, "Bréguet-Cluster A", "Serveur de gestion de projets");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("101", "smtp-new", NULL, "Bréguet-Cluster A", "Server d'envoi de mails Bréguet");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("102", "prd-mail", NULL, "Bréguet-Cluster A", "Routage-Mail-Supelec");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("103", "smtp2", NULL, "Bréguet-Cluster A", "Serveur d'envoi de mail principal de Bréguet");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("104", "bal-eleves", NULL, "Bréguet-Cluster A", "Mailhost des boites aux lettre élèves (cursus Supelec)");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("105", "mxcs2", NULL, "Bréguet-Cluster A", "MX (routeur de mail) pour centralesupelec.fr (secondaire)");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("106", "mxcs1", NULL, "Bréguet-Cluster A", "MX (routeur de mail) pour centralesupelec.fr (principal)");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("107", "mail-workflow", NULL, "Bréguet-Cluster A", "Routage de mail");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("108", "mail.supelec.fr", NULL, "Bréguet-Cluster A", "MX (routage de mail) pour domaine supelec.fr");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("109", "PRD-MX2.ecp.fr", NULL, "Bréguet-Cluster B", "routage de mail");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("110", "OLD-MX1", NULL, "Bréguet-Cluster B", "routage de mail");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("111", "PRD-MX-CS-3", NULL, "Bréguet-Cluster B", "routage de mail");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("112", "PRD-SMTP4", NULL, "Bréguet-Cluster B", "Serveur de mail sortants pour serveurs CS");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("113", "PRD-MX1.ecp.fr", NULL, "Bréguet-Cluster B", "routage de mail");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("114", "PRD-MX.centralesupelec.fr", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("115", "mobility-sogo", NULL, "Bréguet-Cluster A", "Webmail et caldendriers ex-Supélec (en voie de migration sur nouveau serveur)");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("116", "sogo.centralesupelec.fr", NULL, "Bréguet-Cluster A", "Nouveau serveur de Webmail/Calendrier (en cours d'installation)");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("117", "PRD-SOGO-CS", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("118", "PRD-SYMPA", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("119", "PRD-CS-LIST", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("120", "webmail2", NULL, "Bréguet-Cluster A", "Serveur Webmail temporaire pour les personnes changeant de campus");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("121", "PRD-FE-EXALEAD", NULL, "Bréguet-Cluster B", "Obsolete");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("122", "dir-staff.supelec.centralesupelec.local", NULL, "Bréguet-Cluster A", "Serveur de partage de fichiers Windiows ex-Bréguet (en voie de disparition)");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("123", "dir-students.supelec.centralesupelec.local", NULL, "Bréguet-Cluster A", "Serveur de fichiers des comptes élèves (Cursus Supélec)");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("124", "PRD-DISIWEB", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("125", "PRD-ESPACEDR", NULL, "Bréguet-Cluster B", "Espace partagé DR - Obsolete ?");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("126", "new-mathfi1.mics.centralesupelec.fr", NULL, "Bréguet-Cluster A", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("127", "PRD-TS_LGI", NULL, "Bréguet-Cluster A", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("128", "DEV-MICS", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("129", "PRD-SESAM2", NULL, "Bréguet-Cluster B", "MICS - Obsolete ?");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("130", "PRD-SESAM1", NULL, "Bréguet-Cluster B", "MICS - Obsolete ?");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("131", "PRD-DATASERVER", NULL, "Bréguet-Cluster A", "Serveur de fichiers partagés");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("132", "PRD-FILESERVER", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("133", "PRD-PHOTOTHEQUE", NULL, "Bréguet-Cluster A", "Serveur Photo/video service comm");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("134", "ssent.SSE.supelec.fr", NULL, "Bréguet-Cluster A", "Serveur Windows SSE (Luc Batalie) prévoir le remplacement par un service corporate");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("135", "si-linux", NULL, "Bréguet-Cluster A", "Serveur du départment d'enseignement informatique (cf Dom. Marcadet)");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("136", "syndi", NULL, "Bréguet-Cluster A", "Serveur des syndicats");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("137", "speedy2", NULL, "Bréguet-Cluster A", "Serveur du département d'enseignement informatique");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("138", "ssent-2.SSE.supelec.fr", NULL, "Bréguet-Cluster A", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("139", "crig-lab-minsi8", NULL, "Bréguet-Cluster A", "VM de TP Unix. cf Thibault Le Meur. Obsolète");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("140", "PRD-MSIO", NULL, "Bréguet-Cluster B", "Cursus MSIO");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("141", "PRD-LGI-TSLABO", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("142", "TST-CENTRALBADGE", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("143", "gif-adpsmgr", NULL, "Bréguet-Cluster A", "Serveur AD");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("144", "test-ADCS-DirSync", NULL, "Bréguet-Cluster A", "Serveur de test de synchronisation AD vers MS365");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("145", "dc-students.students.gif.supelec.centralesupelec.local", NULL, "Bréguet-Cluster A", "Server Active Directory Eleves");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("146", "test-ADCS-Gif", NULL, "Bréguet-Cluster A", "AD test");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("147", "test-ADCS-HEAD", NULL, "Bréguet-Cluster A", "AD de test");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("148", "dc-gif.gif.supelec.centralesupelec.local", NULL, "Bréguet-Cluster A", "Serveur AD");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("149", "DC-STAFF.staff.gif.supelec.centralesupelec.local[new]", NULL, "Bréguet-Cluster A", "Serveur AD");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("150", "dc-metz.metz.supelec.centralesupelec.local", NULL, "Bréguet-Cluster A", "Serveur AD");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("151", "GC-CS-S1-2016", NULL, "Bréguet-Cluster A", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("152", "gvadtest", NULL, "Bréguet-Cluster A", "AD de test");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("153", "test-ADCS-AzureAD", NULL, "Bréguet-Cluster A", "AD test");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("154", "dc-supelec.supelec.centralesupelec.local", NULL, "Bréguet-Cluster A", "composant AD");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("155", "dc-stud-rennes.eleves.rennes.supelec.centralesupelec.local", NULL, "Bréguet-Cluster A", "composant AD");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("156", "dc-rennes.rennes.supelec.centralesupelec.local", NULL, "Bréguet-Cluster A", "AD");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("157", "rsro-supelec.supelec.centralesupelec.local", NULL, "Bréguet-Cluster A", "AD en lecture seule (OBSOLETE ?)");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("158", "gc-centralesup.centralesupelec.local", NULL, "Bréguet-Cluster A", "AD Global Catalog");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("159", "PRD-REPLICA-STUDENTS-RENNES-SUPELEC", NULL, "Bréguet-Cluster B", "Serveur AD");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("160", "PRD-REPLICA-STUDENTS-GIF-SUPELEC", NULL, "Bréguet-Cluster B", "Serveur AD");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("161", "PRD-REPLICA-STAFF-GIF-SUPELEC", NULL, "Bréguet-Cluster B", "Serveur AD");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("162", "PRD-REPLICA-SUPELEC", NULL, "Bréguet-Cluster B", "Serveur AD");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("163", "PRD-REPLICA-RENNES-SUPELEC", NULL, "Bréguet-Cluster B", "Serveur AD");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("164", "PRD-AD-1", NULL, "Bréguet-Cluster B", "Serveur AD");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("165", "PRD-REPLICA-GIF-SUPELEC", NULL, "Bréguet-Cluster B", "Serveur AD");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("166", "PRD-DIRSYNC", NULL, "Bréguet-Cluster B", "Synchro AD->o365");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("167", "PRD-ADCS1", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("168", "TST-ADCS1", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("169", "PRD-ADCS2", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("170", "TST-SCCM", NULL, "Bréguet-Cluster A", "Obsolete: ancien serveur de test SCCM");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("171", "PRD-CAS2.ecp.fr", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("172", "PRD-CAS2.centralesupelec.fr", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("173", "cs-authcas", NULL, "Bréguet-Cluster A", "Obsolete: ancien serveur d'authentification CAS");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("175", "fede", NULL, "Bréguet-Cluster A", "Authentification Shibboleth");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("174", "cas", NULL, "Bréguet-Cluster A", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("176", "GVEQUITRACK", NULL, "Bréguet-Cluster A", "Serveur d'impression");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("177", "srv-printer", NULL, "Bréguet-Cluster A", "Serveur d'impression du Personnel Bréguet");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("178", "DEV-GESPAGE", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("179", "clone_eteint_campus_ldap_cs", NULL, "Bréguet-Cluster B", "Archive");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("180", "PRD-CAMPUS.ldap.centralesupelec.fr", NULL, "Bréguet-Cluster B", "Obsolete");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("181", "PRD-MAIL.ldap.ecp.fr", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("182", "TST2.LDAP.ecp.fr", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("183", "PRD-BACKUP-LDAP", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("184", "PRD-MAIL.ldap.centralesupelec.fr", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("185", "TST-LDAP.centralesupelec.fr", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("186", "maestro-tst.ldap.centralesupelec.fr", NULL, "Bréguet-Cluster A", "Server LDAP de test");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("187", "saclay1.ldap.centralesupelec.fr", NULL, "Bréguet-Cluster A", "Annuaire openldap réplica Gif");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("188", "maestro-dev.ldap.centralesupelec.fr", NULL, "Bréguet-Cluster A", "Serveur LDAP maitre (environnement de développement)");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("189", "maestro.ldap.centralesupelec.fr", NULL, "Bréguet-Cluster A", "Annuaire LDAP maitre");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("190", "saclay2.ldap.centralesupelec.fr", NULL, "Bréguet-Cluster A", "Serveur LDAP cache (nouvel annuaire LDAP-CS)");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("191", "public1.ldap.centralesupelec.fr", NULL, "Bréguet-Cluster A", "Serveur LDAP cache public (nouvel annuaire LDAP-CS)");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("192", "gif_ldapcs2", NULL, "Bréguet-Cluster A", "Cache LDAP-CS");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("193", "public2.ldap.centralesupelec.fr", NULL, "Bréguet-Cluster A", "Second serveur Public LDAP-CS");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("194", "clone_eteint_ldap_ann_cs", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("195", "RE7-LDAPANN-CS", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("196", "PRD-BACKUP.ldap.centralesupelec.fr", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("197", "TST-CS.LDAP.ecp.fr", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("198", "ldapauth-perso", NULL, "Bréguet-Cluster A", "Serveur cache LDAP pour l'authentification. De moisnen moins utilis");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("199", "ldapauth-elv", NULL, "Bréguet-Cluster A", "Serveur cache LDAP d'authentification (en cours de migration)");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("200", "ldap-master", NULL, "Bréguet-Cluster A", "Serveur LDAP maître pour l'annuaire LDAP-S");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("201", "TST-SUPELEC.LDAP.ecp.fr", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("202", "cs-ldap", NULL, "Bréguet-Cluster A", "Méta-annuaire LDAP de transition");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("203", "cs-ldap2", NULL, "Bréguet-Cluster A", "Méta-annuaire LDAP de transition (backup)");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("204", "PRD-CS.LDAP.ecp.fr", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("205", "myadmin.centralesupelec.fr", NULL, "Bréguet-Cluster A", "Serveur de gestion de comptes (partie admin de monCompte)");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("206", "hub-photos.centralesupelec.fr", NULL, "Bréguet-Cluster A", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("207", "Clone-Orchestra-20180713", NULL, "Bréguet-Cluster A", "Obsolete: à supprimer");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("208", "PRD-ETL_restored", NULL, "Bréguet-Cluster B", "Script alimentation BDD->LDAP");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("209", "imhotep-pub", NULL, "Bréguet-Cluster A", "Serveur de gestion des mots de passe des vacataires ex-Gif. En voie de migration vers Orchestra");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("210", "webapp-priv", NULL, "Bréguet-Cluster A", "Service de gestion de compte et d'infra DISI (composant IMhotep)");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("211", "mercury-new", NULL, "Bréguet-Cluster A", "Bus de message pour la gestion des comptes LDAP-S");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("212", "mercury", NULL, "Bréguet-Cluster A", "Bus de message pour la gestion des comptes LDAP-S");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("213", "webapp-pub", NULL, "Bréguet-Cluster A", "Composante publique d'Imhotep");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("214", "orchestra-dev.centralesupelec.fr", NULL, "Bréguet-Cluster A", "Orchestrateur, utilisé pour la chaine d'activation et de modification de mots de passe");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("215", "orchestra.centralesupelec.fr", NULL, "Bréguet-Cluster A", "Serveur d'orchestration (nouvelle chaine de comptes)");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("216", "PRD-ETL", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("217", "DEV-SIG", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("218", "PRD-SIG", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("219", "PRD-SIG2", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("220", "studentmail.centralesupelec.fr", NULL, "Bréguet-Cluster A", "Serveur d'affectation d'adresse email étudiants");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("221", "egesco", NULL, "Bréguet-Cluster A", "Serveur de gestion des contrats de recherche");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("222", "PRD-MESOCENTRE", NULL, "Bréguet-Cluster A", "Serveur Web Mesocentre");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("223", "ctc-front.centralesupelec.fr", NULL, "Bréguet-Cluster A", "Evenement terminé - à éteindre ? (contact : Ayoub Sbai)");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("224", "ctc-api.centralesupelec.fr", NULL, "Bréguet-Cluster A", "Evenement terminé - à éteindre ? (contact : Ayoub Sbai)");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("225", "PRD-GITLAB", NULL, "Bréguet-Cluster A", "Serveur de gestion de projet et versionning de code Gitlab");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("226", "gitlab-runner3.centralesupelec.fr", NULL, "Bréguet-Cluster A", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("227", "gitlab-runner1.centralesupelec.fr", NULL, "Bréguet-Cluster A", "composant Worker de Gitlab de recherche");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("228", "TST-GITLAB", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("229", "jupyter-saclay4.centralesupelec.fr", NULL, "Bréguet-Cluster A", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("230", "jupyter-saclay.centralesupelec.fr", NULL, "Bréguet-Cluster A", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("231", "jupiter-saclay3.centralesupelec.fr", NULL, "Bréguet-Cluster A", "Serveur de playbook Python");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("232", "jupyter-saclay2.centralesupelec.fr", NULL, "Bréguet-Cluster A", "Serveur de playbook Python");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("233", "test-ADCS-Chat", NULL, "Bréguet-Cluster A", "AD de test");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("234", "cloud4u.centralesupelec.fr", NULL, "Bréguet-Cluster A", "Portail du cloud privé éducation: VMs à la demande");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("235", "supforge2", NULL, "Bréguet-Cluster A", "Forge logicielle (département informatique). Cf Fabrice Popineau pour arrêt");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("236", "ctc-worker.centralesupelec.fr", NULL, "Bréguet-Cluster A", "Evenement terminé - à éteindre ? (contact : Ayoub Sbai)");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("237", "eCampus-ldap", NULL, "Bréguet-Cluster A", "Serveur LDAP pour Edunao");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("238", "PRD-WORDPRESS", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("239", "TST-EMENTOR2", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("240", "TST-EMENTOR", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("241", "TST-DBEMENTOR", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("242", "DEV-EMENTOR", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("243", "PRD-DBEMENTOR2", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("244", "DEV-DBEMENTOR", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("247", "PRD-DBEMENTOR", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("248", "PRD-EMENTOR", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("246", "PRD-DBEMENTOR-EN", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("249", "cafpa-recette", NULL, "Bréguet-Cluster A", "Serveur de recette de l'application d'évaluation par les pairs Peeramid");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("250", "peeramid", NULL, "Bréguet-Cluster A", "Application peeramid de production (vérifier si la version de Metz");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("251", "infnts1.v2", NULL, "Bréguet-Cluster A", "Serveur de licences education Bréguet");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("252", "PRD-CAMPUSLIC", NULL, "Bréguet-Cluster A", "serveur licences");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("4", "doors1", NULL, "Bréguet-Cluster A", "Serveur de licence Bréguet ????");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("253", "PRD-LICEDU", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("254", "doors", NULL, "Bréguet-Cluster A", "Serveur de licence Bréguet ???");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("255", "PRD-LICECP", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("256", "moodle-new", NULL, "Bréguet-Cluster A", "Serveur LMS cursus Supéle");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("257", "cs-survey", NULL, "Bréguet-Cluster A", "Application de questionnaires en lignes (en cours de migration)");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("258", "survey.centralesupelec.fr", NULL, "Bréguet-Cluster A", "Nouveau serveur d'enquêtes en lignes LimeSurvey");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("260", "trainingadvisor2", NULL, "Bréguet-Cluster A", "Serveur d'information expérience internationnale (cursus ECP)");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("261", "trainingadvisor", NULL, "Bréguet-Cluster A", "Serveur d'information expérience internationnale cursus Supelec");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("259", "trainingadvisor-dev", NULL, "Bréguet-Cluster A", "Serveur de Dev. d'information expérience internationale");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("262", "ministudio-dev", NULL, "Bréguet-Cluster A", "Système de développement des applications du ministudio");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("264", "PRD-WSAPOGEE", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("263", "PRD-UBICASTWK", NULL, "Bréguet-Cluster A", "Ubicast: serveur de gestion de jobs de conversion vidéo");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("265", "PRD-APOSN", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("266", "TST-APOBDD450", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("267", "PRD-APOREINS", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("268", "PRD-MONDOSSIER", NULL, "Bréguet-Cluster B", "Dev custom pour affichage notes apogee");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("269", "TST-ENTETUDES", NULL, "Bréguet-Cluster B", "Obsolete");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("270", "TST-EVALENS", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("271", "TST-EVALBDD", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("272", "PRD-EVALENS", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("273", "myway-preprod.centralesupelec.fr", NULL, "Bréguet-Cluster A", "Serveur MyWay (pré-production)");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("274", "myway.centralesupelec.fr", NULL, "Bréguet-Cluster A", "Serveur de collecte de choix de des élèves et d'affectation de cours");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("276", "PRD-STAGES", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("275", "DEV-STAGES", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("277", "PRD-PSTAGE2", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("278", "clone-p-gestion-maj", NULL, "Bréguet-Cluster A", "Backup Live hotstandby du serveur Frontend de Base-Eleves");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("279", "p-gestion", NULL, "Bréguet-Cluster A", "Serveur frontend de la gestion de scolarité Cursus Supélec (Base-Eleves)");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("280", "clone-p-gestion-orig", NULL, "Bréguet-Cluster A", "Obsolete: backup de la VM du frontend  Base-Eleves");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("281", "p-gestion-orig", NULL, "Bréguet-Cluster A", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("284", "portail-appli", NULL, "Bréguet-Cluster A", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("283", "p-gestion.old", NULL, "Bréguet-Cluster A", "Backup frontal du portail scol Supelec BAse-Eleves");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("282", "dev-scolarite", NULL, "Bréguet-Cluster A", "Base de données de l'appli Base-Eleves (envir. de developpement)");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("285", "ent-reloaded", NULL, "Bréguet-Cluster A", "ENT des élèves du cursus Supélec");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("286", "apply-sql", NULL, "Bréguet-Cluster A", "Serveur de developpement pour l'application d'application en ligne");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("287", "apply-prod", NULL, "Bréguet-Cluster A", "Application de candidature en ligne");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("288", "napply-gec.centralesupelec.fr", NULL, "Bréguet-Cluster A", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("289", "PRD-CCS-SRV", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("291", "PRD-DONOR", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("290", "PRD-WEBCONCOURS", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("292", "GIF-PRODON02", NULL, "Bréguet-Cluster A", "Serveur de gestion des dons Fondation (ex-Supélec)");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("293", "PRD-WEBEXED", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("294", "csee-ldap1", NULL, "Bréguet-Cluster A", "Serveur LDAP d'intégration EDUNAO pour l'ExED");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("295", "prd-web-evt-exed.centralesupelec.fr", NULL, "Bréguet-Cluster A", "Serveur Web Exed");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("296", "ms-surv", NULL, "Bréguet-Cluster A", "Obsolete: ancien serveur LimeSurvey dédiée marketting startégique");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("297", "PRD-UNICAMPUS-WEB", NULL, "Bréguet-Cluster B", "Gestion Badges/Izly");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("298", "PRD2-BIBKOHA", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("299", "PRD-BIBNUM-INTRA", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("300", "PRD-BIBNUM-EXTRA", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("301", "gvbibliotheca", NULL, "Bréguet-Cluster A", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("302", "gvsedeco", NULL, "Bréguet-Cluster A", "Solution d'impression élèves");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("303", "OLD-BIBKOHA-CS", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("304", "TST-BIBKOHA-CS", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("305", "compta1000-3", NULL, "Bréguet-Cluster A", "Comptabilité ex-Supélec");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("307", "tst-sifac-centralesupelec", NULL, "Bréguet-Cluster A", "Serveur SIFAC (test)");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("306", "compta1000-2", NULL, "Bréguet-Cluster A", "Ancien serveur compta/reporting ex-Supélec (conservé pour archives)");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("309", "PRD-SIFAC-CS-CLONE-BFA", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("308", "prd-sifac-centralesupelec", NULL, "Bréguet-Cluster A", "Serveur SIFAC (Production)");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("310", "CLONE-PRD-SIFAC-CS", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("312", "TST-SIFAC-CS", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("311", "PRD-SIFAC-CS", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("314", "DEV-SAPBO", NULL, "Bréguet-Cluster A", "Serveur BO developpement");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("313", "PRD-SAPBO", NULL, "Bréguet-Cluster A", "Serveur BO ");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("315", "TST-DWH-JOBS", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("316", "TST-DWH-BDD", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("318", "arcole2", NULL, "Bréguet-Cluster A", "Serveur de Gestion RH ex-Supélec (conservé pour archives)");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("317", "DEV-REPORTINGDR", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("319", "p-arcole", NULL, "Bréguet-Cluster A", "Frontend de l'application de gestion RH ex-Supélec (conservé pour archive)");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("320", "PRD-VIRTUALIA", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("321", "PRD-VIRTUALIA-NET", NULL, "Bréguet-Cluster B", "gestion congés");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("323", "PRD-EVRP", NULL, "Bréguet-Cluster B", "Evaluation des risques professionnels");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("324", "TST-EVRP", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("322", "TST-VIRTUALIA", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("325", "PRD-ACADEM", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("327", "request", NULL, "Bréguet-Cluster A", "Serveur de gestion de demandes RT pour DISI et autres services");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("326", "DEV-ACADEM", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("328", "ask.centralesupelec.fr", NULL, "Bréguet-Cluster A", "VM pour un nouveau système de gestion de demandes (prévu pour RT à l'origine, pas mis en produciton)");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("329", "TST-WORKEY", NULL, "Bréguet-Cluster B", "Obsolete");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("330", "screencomposer", NULL, "Bréguet-Cluster A", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("331", "caldav-affdyn.affichage.centralesupelec.fr", NULL, "Bréguet-Cluster A", "Obsolete: service de gestion de calendrier des tablettes d'affichage dynamique, remplacé par des appels WebServices");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("332", "crig-innes", NULL, "Bréguet-Cluster A", "Ancien serveur d'affichage dynamique (écrans d'information Bréguet, Rennes, Metz)");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("333", "PRD-LDAPANN.centralesupelec.fr", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("334", "resa-salles.centralesupelec.fr", NULL, "Bréguet-Cluster A", "Outil de réservation de salles");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("335", "TST-Espace-CRSA", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("336", "PRD-WEBCRSA", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("337", "PRD-EM2C-S04", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("339", "jobfair", NULL, "Bréguet-Cluster A", "Serveur Web JobFair");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("338", "prd-disiweb", NULL, "Bréguet-Cluster A", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("340", "PRD-APPLIWEB", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("341", "integrer-supelec", NULL, "Bréguet-Cluster A", "Obsolete: ancien serveur Web");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("342", "prd-time-asso.centralesupelec.fr", NULL, "Bréguet-Cluster A", "Serveur Web association TIME");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("345", "TST-WEB-LABOS", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("344", "PRD-WEBCS_restored", NULL, "Bréguet-Cluster B", "Obsolete");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("343", "TST-DRUPAL-CS", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("347", "PRD-LAMP.ecp.fr", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("346", "TST-WEBCS", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("349", "PP-WEB-CS", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("350", "PRD-CANDICASA", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("348", "PRD-LAMP2", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("351", "PRD-LIONCEAU", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("352", "PRD-MYSQL", NULL, "Bréguet-Cluster B", "BDD");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("355", "PRD-LGI-SRV.ecp.fr_newrestored", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("353", "PRD-POSTGRES9", NULL, "Bréguet-Cluster B", "BDD");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("356", "PRD-LGIWEB", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("358", "PRD-CVN", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("357", "PRD-DIGIPLANTE", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("354", "PRD-WEBECC", NULL, "Bréguet-Cluster B", "Casablanca");
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("359", "PRD-GRR-MSSMAT", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("360", "PRD-DDECK", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("361", "PRD-WEB-GEEPS", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("362", "PRD-CAHIERLABO-SPMS", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("245", "OLD-CLAROLINE", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("363", "PRD-FREEMOVE", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("364", "PRD-ERAMUNDUS", NULL, "Bréguet-Cluster B", NULL);
INSERT INTO `virtualMachines` (`_id`, `label`, `filePath`, `campus`, `comment`) VALUES("365", "PRD-LGI-SRV.ecp.fr", NULL, "Bréguet-Cluster B", NULL);
