INSERT INTO `domains` (`_id`, `label`, `parentId`) VALUES ('1', 'Non Classé', '1');
INSERT INTO `domains` (`_id`, `label`, `parentId`) VALUES ('2', 'Parc Informatique', '2');
INSERT INTO `domains` (`_id`, `label`, `parentId`) VALUES ('3', 'Réseaux', '3');
INSERT INTO `domains` (`_id`, `label`, `parentId`) VALUES ('4', 'Virtualisation', '4');
INSERT INTO `domains` (`_id`, `label`, `parentId`) VALUES ('5', 'Mail et Partage', '5');
INSERT INTO `domains` (`_id`, `label`, `parentId`) VALUES ('6', 'Habilitations et Accès', '6');
INSERT INTO `domains` (`_id`, `label`, `parentId`) VALUES ('7', 'Recherche', '7');
INSERT INTO `domains` (`_id`, `label`, `parentId`) VALUES ('8', 'Pédagogie', '8');
INSERT INTO `domains` (`_id`, `label`, `parentId`) VALUES ('9', 'Scolarité', '9');
INSERT INTO `domains` (`_id`, `label`, `parentId`) VALUES ('10', 'Recrutements et Partenariats', '10');
INSERT INTO `domains` (`_id`, `label`, `parentId`) VALUES ('11', 'Gestion Admin', '11');
INSERT INTO `domains` (`_id`, `label`, `parentId`) VALUES ('12', 'Portail de Services', '12');
INSERT INTO `domains` (`_id`, `label`, `parentId`) VALUES ('13', 'Web', '13');
INSERT INTO `domains` (`label`, `parentId`) VALUES ('Divers', '1');
INSERT INTO `domains` (`label`, `parentId`) VALUES ('Obsolète', '1');
INSERT INTO `domains` (`label`, `parentId`) VALUES ('Gestion de parc', '2');
INSERT INTO `domains` (`label`, `parentId`) VALUES ('Divers', '3');
INSERT INTO `domains` (`label`, `parentId`) VALUES ('DHCP', '3');
INSERT INTO `domains` (`label`, `parentId`) VALUES ('DNS', '3');
INSERT INTO `domains` (`label`, `parentId`) VALUES ('Gestion', '3');
INSERT INTO `domains` (`label`, `parentId`) VALUES ('Métrologie', '3');
INSERT INTO `domains` (`label`, `parentId`) VALUES ('Radius', '3');
INSERT INTO `domains` (`label`, `parentId`) VALUES ('Sécurité', '3');
INSERT INTO `domains` (`label`, `parentId`) VALUES ('SSH', '3');
INSERT INTO `domains` (`label`, `parentId`) VALUES ('Supervision', '3');
INSERT INTO `domains` (`label`, `parentId`) VALUES ('VLAN', '3');
INSERT INTO `domains` (`label`, `parentId`) VALUES ('Temps', '3');
INSERT INTO `domains` (`label`, `parentId`) VALUES ('VPN', '3');
INSERT INTO `domains` (`label`, `parentId`) VALUES ('Gestion', '4');
INSERT INTO `domains` (`label`, `parentId`) VALUES ('Logs', '4');
INSERT INTO `domains` (`label`, `parentId`) VALUES ('Sauvegardes', '4');
INSERT INTO `domains` (`label`, `parentId`) VALUES ('Template', '4');
INSERT INTO `domains` (`label`, `parentId`) VALUES ('Virtualisation', '4');
INSERT INTO `domains` (`label`, `parentId`) VALUES ('Archive', '5');
INSERT INTO `domains` (`label`, `parentId`) VALUES ('GED', '5');
INSERT INTO `domains` (`label`, `parentId`) VALUES ('Gestion de projets', '5');
INSERT INTO `domains` (`label`, `parentId`) VALUES ('Mail', '5');
INSERT INTO `domains` (`label`, `parentId`) VALUES ('Moteur de recherche', '5');
INSERT INTO `domains` (`label`, `parentId`) VALUES ('Partage', '5');
INSERT INTO `domains` (`label`, `parentId`) VALUES ('Accès physiques', '6');
INSERT INTO `domains` (`label`, `parentId`) VALUES ('AD', '6');
INSERT INTO `domains` (`label`, `parentId`) VALUES ('Authentification', '6');
INSERT INTO `domains` (`label`, `parentId`) VALUES ('Impression', '6');
INSERT INTO `domains` (`label`, `parentId`) VALUES ('LDAP', '6');
INSERT INTO `domains` (`label`, `parentId`) VALUES ('MonCompte', '6');
INSERT INTO `domains` (`label`, `parentId`) VALUES ('Workflow', '6');
INSERT INTO `domains` (`label`, `parentId`) VALUES ('Contrats de recherche', '7');
INSERT INTO `domains` (`label`, `parentId`) VALUES ('MesoCentre', '7');
INSERT INTO `domains` (`label`, `parentId`) VALUES ('Coding', '8');
INSERT INTO `domains` (`label`, `parentId`) VALUES ('Edunao', '8');
INSERT INTO `domains` (`label`, `parentId`) VALUES ('Innovation', '8');
INSERT INTO `domains` (`label`, `parentId`) VALUES ('Licences', '8');
INSERT INTO `domains` (`label`, `parentId`) VALUES ('Moodle', '8');
INSERT INTO `domains` (`label`, `parentId`) VALUES ('Sondages', '8');
INSERT INTO `domains` (`label`, `parentId`) VALUES ('TA', '8');
INSERT INTO `domains` (`label`, `parentId`) VALUES ('Vidéo', '8');
INSERT INTO `domains` (`label`, `parentId`) VALUES ('Centrale', '9');
INSERT INTO `domains` (`label`, `parentId`) VALUES ('eSUP', '9');
INSERT INTO `domains` (`label`, `parentId`) VALUES ('Evaluation des enseignements', '9');
INSERT INTO `domains` (`label`, `parentId`) VALUES ('MyWay', '9');
INSERT INTO `domains` (`label`, `parentId`) VALUES ('Personalisation des parcours', '9');
INSERT INTO `domains` (`label`, `parentId`) VALUES ('Stages', '9');
INSERT INTO `domains` (`label`, `parentId`) VALUES ('Supélec', '9');
INSERT INTO `domains` (`label`, `parentId`) VALUES ('Candidatures', '10');
INSERT INTO `domains` (`label`, `parentId`) VALUES ('Concours', '10');
INSERT INTO `domains` (`label`, `parentId`) VALUES ('CRM', '10');
INSERT INTO `domains` (`label`, `parentId`) VALUES ('ExEd', '10');
INSERT INTO `domains` (`label`, `parentId`) VALUES ('Marketing', '10');
INSERT INTO `domains` (`label`, `parentId`) VALUES ('Badges', '11');
INSERT INTO `domains` (`label`, `parentId`) VALUES ('Bibliothèque', '11');
INSERT INTO `domains` (`label`, `parentId`) VALUES ('Finances', '11');
INSERT INTO `domains` (`label`, `parentId`) VALUES ('Reporting', '11');
INSERT INTO `domains` (`label`, `parentId`) VALUES ('RH', '11');
INSERT INTO `domains` (`label`, `parentId`) VALUES ('Sécurité', '11');
INSERT INTO `domains` (`label`, `parentId`) VALUES ('Vacataires', '11');
INSERT INTO `domains` (`label`, `parentId`) VALUES ('Workflow', '11');
INSERT INTO `domains` (`label`, `parentId`) VALUES ('Affichage', '12');
INSERT INTO `domains` (`label`, `parentId`) VALUES ('Annuaire', '12');
INSERT INTO `domains` (`label`, `parentId`) VALUES ('Resa', '12');
INSERT INTO `domains` (`label`, `parentId`) VALUES ('Fondation', '13');
INSERT INTO `domains` (`label`, `parentId`) VALUES ('Partage', '13');
INSERT INTO `domains` (`label`, `parentId`) VALUES ('Web', '13');
INSERT INTO `domains` (`label`, `parentId`) VALUES ('Web Institutionnel', '13');
INSERT INTO `domains` (`label`, `parentId`) VALUES ('Web Associations', '13');
INSERT INTO `domains` (`label`, `parentId`) VALUES ('Web institutionnel', '13');
INSERT INTO `domains` (`label`, `parentId`) VALUES ('Web Labo', '13');