INSERT INTO `Domains` (`_id`, `Label`, `ParentID`) VALUES ('1', 'Non Classé', '1');
INSERT INTO `Domains` (`Label`, `ParentID`) VALUES ('Divers', '1');
INSERT INTO `Domains` (`Label`, `ParentID`) VALUES ('Obsolète', '1');
INSERT INTO `Domains` (`_id`, `Label`, `ParentID`) VALUES ('2', 'Parc Informatique', '2');
INSERT INTO `Domains` (`Label`, `ParentID`) VALUES ('Gestion de parc', '2');
INSERT INTO `Domains` (`_id`, `Label`, `ParentID`) VALUES ('3', 'Réseaux', '3');
INSERT INTO `Domains` (`Label`, `ParentID`) VALUES ('Divers', '3');
INSERT INTO `Domains` (`Label`, `ParentID`) VALUES ('DHCP', '3');
INSERT INTO `Domains` (`Label`, `ParentID`) VALUES ('DNS', '3');
INSERT INTO `Domains` (`Label`, `ParentID`) VALUES ('Gestion', '3');
INSERT INTO `Domains` (`Label`, `ParentID`) VALUES ('Métrologie', '3');
INSERT INTO `Domains` (`Label`, `ParentID`) VALUES ('Radius', '3');
INSERT INTO `Domains` (`Label`, `ParentID`) VALUES ('Sécurité', '3');
INSERT INTO `Domains` (`Label`, `ParentID`) VALUES ('SSH', '3');
INSERT INTO `Domains` (`Label`, `ParentID`) VALUES ('Supervision', '3');
INSERT INTO `Domains` (`Label`, `ParentID`) VALUES ('VLAN', '3');
INSERT INTO `Domains` (`Label`, `ParentID`) VALUES ('Temps', '3');
INSERT INTO `Domains` (`Label`, `ParentID`) VALUES ('VPN', '3');
INSERT INTO `Domains` (`_id`, `Label`, `ParentID`) VALUES ('4', 'Virtualisation', '4');
INSERT INTO `Domains` (`Label`, `ParentID`) VALUES ('Gestion', '4');
INSERT INTO `Domains` (`Label`, `ParentID`) VALUES ('Logs', '4');
INSERT INTO `Domains` (`Label`, `ParentID`) VALUES ('Sauvegardes', '4');
INSERT INTO `Domains` (`Label`, `ParentID`) VALUES ('Template', '4');
INSERT INTO `Domains` (`Label`, `ParentID`) VALUES ('Virtualisation', '4');
INSERT INTO `Domains` (`_id`, `Label`, `ParentID`) VALUES ('5', 'Mail et Partage', '5');
INSERT INTO `Domains` (`Label`, `ParentID`) VALUES ('Archive', '5');
INSERT INTO `Domains` (`Label`, `ParentID`) VALUES ('GED', '5');
INSERT INTO `Domains` (`Label`, `ParentID`) VALUES ('Gestion de projets', '5');
INSERT INTO `Domains` (`Label`, `ParentID`) VALUES ('Mail', '5');
INSERT INTO `Domains` (`Label`, `ParentID`) VALUES ('Moteur de recherche', '5');
INSERT INTO `Domains` (`Label`, `ParentID`) VALUES ('Partage', '5');
INSERT INTO `Domains` (`_id`, `Label`, `ParentID`) VALUES ('6', 'Habilitations et Accès', '6');
INSERT INTO `Domains` (`Label`, `ParentID`) VALUES ('Accès physiques', '6');
INSERT INTO `Domains` (`Label`, `ParentID`) VALUES ('AD', '6');
INSERT INTO `Domains` (`Label`, `ParentID`) VALUES ('Authentification', '6');
INSERT INTO `Domains` (`Label`, `ParentID`) VALUES ('Impression', '6');
INSERT INTO `Domains` (`Label`, `ParentID`) VALUES ('LDAP', '6');
INSERT INTO `Domains` (`Label`, `ParentID`) VALUES ('MonCompte', '6');
INSERT INTO `Domains` (`Label`, `ParentID`) VALUES ('Workflow', '6');
INSERT INTO `Domains` (`_id`, `Label`, `ParentID`) VALUES ('7', 'Recherche', '7');
INSERT INTO `Domains` (`Label`, `ParentID`) VALUES ('Contrats de recherche', '7');
INSERT INTO `Domains` (`Label`, `ParentID`) VALUES ('MesoCentre', '7');
INSERT INTO `Domains` (`_id`, `Label`, `ParentID`) VALUES ('8', 'Pédagogie', '8');
INSERT INTO `Domains` (`Label`, `ParentID`) VALUES ('Coding', '8');
INSERT INTO `Domains` (`Label`, `ParentID`) VALUES ('Edunao', '8');
INSERT INTO `Domains` (`Label`, `ParentID`) VALUES ('Innovation', '8');
INSERT INTO `Domains` (`Label`, `ParentID`) VALUES ('Licences', '8');
INSERT INTO `Domains` (`Label`, `ParentID`) VALUES ('Moodle', '8');
INSERT INTO `Domains` (`Label`, `ParentID`) VALUES ('Sondages', '8');
INSERT INTO `Domains` (`Label`, `ParentID`) VALUES ('TA', '8');
INSERT INTO `Domains` (`Label`, `ParentID`) VALUES ('Vidéo', '8');
INSERT INTO `Domains` (`_id`, `Label`, `ParentID`) VALUES ('9', 'Scolarité', '9');
INSERT INTO `Domains` (`Label`, `ParentID`) VALUES ('Centrale', '9');
INSERT INTO `Domains` (`Label`, `ParentID`) VALUES ('eSUP', '9');
INSERT INTO `Domains` (`Label`, `ParentID`) VALUES ('Evaluation des enseignements', '9');
INSERT INTO `Domains` (`Label`, `ParentID`) VALUES ('MyWay', '9');
INSERT INTO `Domains` (`Label`, `ParentID`) VALUES ('Personalisation des parcours', '9');
INSERT INTO `Domains` (`Label`, `ParentID`) VALUES ('Stages', '9');
INSERT INTO `Domains` (`Label`, `ParentID`) VALUES ('Supélec', '9');
INSERT INTO `Domains` (`_id`, `Label`, `ParentID`) VALUES ('10', 'Recrutements et Partenariats', '10');
INSERT INTO `Domains` (`Label`, `ParentID`) VALUES ('Candidatures', '10');
INSERT INTO `Domains` (`Label`, `ParentID`) VALUES ('Concours', '10');
INSERT INTO `Domains` (`Label`, `ParentID`) VALUES ('CRM', '10');
INSERT INTO `Domains` (`Label`, `ParentID`) VALUES ('ExEd', '10');
INSERT INTO `Domains` (`Label`, `ParentID`) VALUES ('Marketing', '10');
INSERT INTO `Domains` (`_id`, `Label`, `ParentID`) VALUES ('11', 'Gestion Admin', '11');
INSERT INTO `Domains` (`Label`, `ParentID`) VALUES ('Badges', '11');
INSERT INTO `Domains` (`Label`, `ParentID`) VALUES ('Bibliothèque', '11');
INSERT INTO `Domains` (`Label`, `ParentID`) VALUES ('Finances', '11');
INSERT INTO `Domains` (`Label`, `ParentID`) VALUES ('Reporting', '11');
INSERT INTO `Domains` (`Label`, `ParentID`) VALUES ('RH', '11');
INSERT INTO `Domains` (`Label`, `ParentID`) VALUES ('Sécurité', '11');
INSERT INTO `Domains` (`Label`, `ParentID`) VALUES ('Vacataires', '11');
INSERT INTO `Domains` (`Label`, `ParentID`) VALUES ('Workflow', '11');
INSERT INTO `Domains` (`_id`, `Label`, `ParentID`) VALUES ('12', 'Portail de Services', '12');
INSERT INTO `Domains` (`Label`, `ParentID`) VALUES ('Affichage', '12');
INSERT INTO `Domains` (`Label`, `ParentID`) VALUES ('Annuaire', '12');
INSERT INTO `Domains` (`Label`, `ParentID`) VALUES ('Resa', '12');
INSERT INTO `Domains` (`_id`, `Label`, `ParentID`) VALUES ('13', 'Web', '13');
INSERT INTO `Domains` (`Label`, `ParentID`) VALUES ('Fondation', '13');
INSERT INTO `Domains` (`Label`, `ParentID`) VALUES ('Partage', '13');
INSERT INTO `Domains` (`Label`, `ParentID`) VALUES ('Web', '13');
INSERT INTO `Domains` (`Label`, `ParentID`) VALUES ('Web Institutionnel', '13');
INSERT INTO `Domains` (`Label`, `ParentID`) VALUES ('Web Associations', '13');
INSERT INTO `Domains` (`Label`, `ParentID`) VALUES ('Web institutionnel', '13');
INSERT INTO `Domains` (`Label`, `ParentID`) VALUES ('Web Labo', '13');